[versions]
minecraft = "1.20"
quilt_mappings = "1.20+build.1"
quilt_loader = "0.19.0-beta.18"

quilted_fabric_api = "7.0.1+0.83.0-1.20"
quilt_kotlin_libraries = "2.1.0+kt.1.8.22+flk.1.9.4"

imgui = "6lytd87M" # 1.0.2 for 1.20
cauldron = "0.1.9"
lib39 = "1.3.1"
devauth = "1.1.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
quilt_kotlin_libraries = { module = "org.quiltmc.quilt-kotlin-libraries:quilt-kotlin-libraries", version.ref = "quilt_kotlin_libraries" }

imgui = { module = "maven.modrinth:imgui-quilt", version.ref = "imgui" }
cauldron = { module = "com.adryd:cauldron", version.ref = "cauldron" }
lib39core = { module = "com.unascribed:lib39-core", version.ref = "lib39" }
devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.0.+" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version = "1.8.22" }
