[versions]
minecraft = "1.19.2"
quilt_mappings = "1.19.2+build.21"
quilt_loader = "0.17.5-beta.9"

quilted_fabric_api = "4.0.0-beta.15+0.63.0-1.19.2"

imgui = "1.0.2+1.19"
cauldron = "0.1.2-alpha2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
quilted_fabric_api_deprecated = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated", version.ref = "quilted_fabric_api" }

imgui = { module = "gay.eviee:imgui-quilt", version.ref = "imgui" }
cauldron = { module = "com.adryd:cauldron", version.ref = "cauldron" }

[bundles]
quilted_fabric_api = ["quilted_fabric_api", "quilted_fabric_api_deprecated"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.0.+" }
